kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "api.fullname" . }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
  mapping.yaml: |
    mappings:
    {{- .Values.mappings | toYaml | nindent 6 }}